### PR TITLE
Add new utilities for Mac

### PR DESCRIPTION
**Pull request by David-C0pperfield**
This is a set of utilities for MacOS users to get fast access to lupdate. Tested on MacBook Pro (2017), macOS 12. 
These two utilities do the same work as those Windows cmd files, while their user experience has been improved for Mac users.
Generate new .ts file for new language

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
The Chinese Simplified translations had been added already, via https://github.com/Jojo-Schmitz/batch_export/pull/13
That Merge commit should not be part of this (or any) PR

**Comment by David-C0pperfield** [comment]
It was accidentally included.

**Comment by Jojo-Schmitz** [comment]
The 2 shell scripts should work on Linux too, I see nothing Mac specific, so just drop the `osx_` prefix

**Comment by David-C0pperfield** [comment]
Cool!

**Comment by Jojo-Schmitz** [comment]
I've `git cherry-pick`ed it.

**Pull request closed without merging**
