### PR TITLE
All my latest improvments, such as the Import/Export folder selection, the export of the current and opened scores, ...

### PR DESCRIPTION
**Pull request by lgvr123**

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
A rebase is needed

**Comment by lgvr123** [comment]
My history seems clean:
history
(source/master being your version). 
There is nothing to rebase (as far as I understand Git). What more are you expecting ?

**Comment by Jojo-Schmitz** [comment]
"This branch cannot be rebased due to conflicts"

**Comment by Jojo-Schmitz** [comment]
And that merge commit doesn't belong there either

**Comment by lgvr123** [comment]
This seems a [common problem](https://cloudaffaire.com/faq/github-cant-rebase-my-feature-branch-this-branch-cannot-be-rebased-due-to-conflicts/).
One of the approach would be that you squash all the individual commits:
JmBy8

**Comment by Jojo-Schmitz** [comment]
`git pull --rebase upstream master`  fix the conflicts, `git rebase --continue; git push -f`

**Comment by lgvr123** [comment]
I'm learning every day !! Next time, I'll do a rebase instead of a merge.
I guess it should be correct now.

**Pull request merged**
