### PR TITLE
4.3.1

### PR DESCRIPTION
**Pull request by lgvr123**
* [Improvement]: Allow to export the files to the dedicated folder when even parsing subdirs
* [Improvement]: Export the main score when only the parts are to be exported and there are no parts
* [Improvement]: New option to rename the files when exported

### CODE REVIEW

**Comment by Jojo-Schmitz** [comment]
a) there's a rebase needed
b) that change to fuding.yml, serious?

**Comment by lgvr123** [comment]
The change to funding.yml was not meant. It is in my template repository on GitHub. Didn't know it would come along with the PR.

In the same time, seeing the amount of changes I made over 2 last years in that plugin, it wouldn't be unlogical.

**Comment by Jojo-Schmitz** [comment]
Darn, now I broke something

**Comment by lgvr123** [comment]
Can I help in some ways ?

**Comment by Jojo-Schmitz** [comment]
Yes, rebase and fix my damage (revert it)

**Comment by lgvr123** [comment]
I'll try

**Comment by lgvr123** [comment]
I think it should be clean now and should should be able to merge my modifications.

**Pull request merged**
